# Lock-file driven dependency fetchers (upstream tarballs themselves come from sources.toml).
#
# Each is a dynamic derivation: a small producer (builder/fetch/*.nu, run under builder-rpc-v0
# with `jig nix-store`) reads the lock file out of `source`, writes one builtin:fetchurl derivation
# per artefact using the hash the lock already carries, plus a derivation assembling them, and
# submits that .drv as its output. The caller gets `builtins.outputOf` it: Nix downloads, caches
# and verifies per file, nothing is hashed by us, no lock file is copied into this repo. Needs
# `dynamic-derivations ca-derivations` on the daemon. Dependencies without a hash in the lock
# (git, path) are rejected by the producer.
#
{
  jig,
  nu,
  system,
  cpu,
  sevenzip ? null,
}:
let
  producers = builtins.path {
    path = ../builder;
    name = "producers";
    # fetch/ plus the helpers it imports from its parent. Build systems and the build pipeline stay
    # out, so editing them does not refetch every lock
    filter =
      p: _:
      builtins.match ".*/builder/(fetch(/.*)?|sys-libs\\.(nu|json)|pep508\\.nu|glob\\.nu)" p != null;
  };

  dynamic' =
    drvName: script: env:
    let
      producer = derivation (
        {
          name = drvName;
          inherit system;
          seed = nu;
          inherit jig;
          builder = "${nu}/bin/nu";
          args = [ "${producers}/${script}" ];
          PATH = "${jig}/bin:${nu}/bin";
          requiredSystemFeatures = [ "builder-rpc-v0" ];
          preferLocalBuild = true;
          __contentAddressed = true;
          outputHashMode = "text";
          outputHashAlgo = "sha256";
        }
        // env
      );
    in
    builtins.outputOf producer.outPath "out";
  # nix names a text-CA output after its derivation minus ".drv": one suffix per stage
  dynamic = name: dynamic' "${name}.drv";

  # for producers that end in `dyn-drv stage` (a second producer) rather than `dyn-drv collect`
  twoStage =
    name: script: env:
    builtins.outputOf (dynamic' "${name}.drv.drv" script env) "out";

in
{
  # Cargo.lock -> a directory cargo accepts as [source.vendored-sources] (crates unpacked, with
  # .cargo-checksum.json). builder/systems/cargo.nu points CARGO_HOME's config at it.
  cargoVendor =
    {
      source,
    }:
    dynamic "cargo-vendor" "fetch/cargo.nu" {
      inherit source;
    };

  # package-lock.json (v2/v3) -> { package-lock.json } with every `resolved` rewritten to
  # file:<store path>; builder/systems/npm.nu swaps it in and `npm ci --offline` verifies integrity itself.
  # `lockFile`: for upstreams that ship none (generated by `uptrack lock`).
  npmDeps =
    {
      source,
      root ? ".",
      lockFile ? null,
    }:
    dynamic "npm-deps" "fetch/npm.nu" {
      inherit source root;
      lockFile = if lockFile == null then "" else lockFile;
    };

  # pnpm-lock.yaml (v9) -> registry/<url path>, a file:// registry builder/systems/pnpm.nu installs from offline.
  pnpmDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "pnpm-deps" "fetch/pnpm.nu" { inherit source root; };

  # yarn.lock (classic v1) -> a yarn offline mirror directory. builder/systems/yarn.nu installs --offline from it.
  yarnDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "yarn-deps" "fetch/yarn.nu" { inherit source root; };

  # bun.lock -> { p/<name>@<version>/ (unpacked), index.json }; builder/systems/bun.nu links them into
  # $BUN_INSTALL_CACHE_DIR under the names bun expects.
  bunDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "bun-deps" "fetch/bun.nu" { inherit source root; };

  # deno.lock (v4+) -> a $DENO_DIR (npm/ and remote/ caches) for `deno … --cached-only`; jsr
  # hashes pin metadata that pins the files, hence two stages (builder/fetch/deno.nu, deno-files.nu).
  denoDeps =
    {
      source,
      root ? ".",
    }:
    twoStage "deno-deps" "fetch/deno.nu" { inherit source root; };

  # uv.lock -> { dist/, vendor/, plan.json }: one artefact per package of the project's runtime
  # closure, installed by builder/systems/pyapp.nu
  pythonDeps =
    {
      source,
      python, # the interpreter wheels must match
      root ? ".",
      extras ? [ ],
      groups ? [ ], # PEP 735 dependency groups of the project
      prefer ? "wheel", # or "sdist": which artefact when the lock has both
      sdist ? [ ], # names always built from sdist (plus sys-libs.nu's and tool.uv.no-binary-package)
      git ? [ ], # { name, path } for the lock's git sources, fetched by the caller (nix/python.nix)
      environ ? "{}", # JSON PEP 508 marker environment overrides
    }:
    twoStage "python-deps" "fetch/pypi.nu" {
      inherit
        source
        root
        cpu
        prefer
        environ
        ;
      pythonVersion = python.version;
      extras = builtins.concatStringsSep "," extras;
      groups = builtins.concatStringsSep "," groups;
      sdist = builtins.concatStringsSep "," sdist;
      git = builtins.concatStringsSep "\n" (map (g: "${g.name}=${g.path}") git);
    };

  # Gemfile.lock (with a CHECKSUMS section, Bundler >= 2.6) -> { vendor/cache/*.gem, Gemfile.lock }
  # for `bundle install --local` (builder/systems/bundler.nu). `lockFile`: for upstreams that commit none.
  gems =
    {
      source,
      root ? ".",
      lockFile ? null,
    }:
    dynamic "gems" "fetch/gems.nu" {
      inherit source root;
      lockFile = if lockFile == null then "" else lockFile;
      gemPlatform = "${cpu}-linux";
    };

  # mix.lock or rebar.lock -> packages/hexpm/<name>-<version>.tar (builder/fetch/hex.nu)
  hexDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "hex-deps" "fetch/hex.nu" { inherit source root; };

  # go.sum -> a GOPROXY=file:// tree (builder/systems/go.nu builds -mod=mod against it, offline). go.sum's
  # h1: hashes are not file hashes, so .mod/.zip sha256s come from `locks` (this repo's
  # locks/go.toml, filled by `uptrack lock`); only this package's subset lands in the output, so
  # unrelated table edits rebuild nothing.
  # locks/hackage.toml, the Haskell version set -> one file+noindex repository for all cabal packages
  hackageSet =
    {
      locks ? ../locks/hackage.toml,
    }:
    dynamic "hackage-set" "fetch/hackage.nu" { inherit locks; };

  # locks/luarocks.toml -> a rocks server directory (.src.rock files + manifest) for luarocks.nu
  luaRocksSet =
    {
      lua,
      locks ? ../locks/luarocks.toml,
    }:
    dynamic "luarocks-set" "fetch/luarocks.nu" {
      inherit locks;
      luaVersion = lua.version;
    };

  goModules =
    {
      source,
      root ? ".",
      locks ? ../locks/go.toml,
    }:
    dynamic "go-modules" "fetch/go.nu" {
      inherit source root locks;
    };

  empty = builtins.path {
    path = ./empty;
    name = "empty";
  };

  # VisualStudio.vsman -> {crt,sdk}/: MSVC CRT with the STL, UCRT and the Windows SDK headers
  # and import libraries for one cpu, the sysroot of the msvc platforms. Unfree (Visual Studio
  # license terms), so CI keeps it out of the public cache.
  windowsSdk =
    { manifest, arch }:
    dynamic "windows-sdk-${arch}" "fetch/winsdk.nu" {
      inherit manifest arch;
      sevenzip = "${sevenzip}";
      sevenzip_drv = sevenzip.drvPath;
    };
}
