# Lock-file driven dependency fetchers (upstream tarballs themselves come from sources.toml).
#
# Each is a dynamic derivation: a small producer (builder/fetch-*.nu, run under builder-rpc-v0
# with `jig nix-store`) reads the lock file out of `source`, writes one builtin:fetchurl derivation
# per artefact using the hash the lock already carries, plus a derivation assembling them, and
# submits that .drv as its output. The caller gets `builtins.outputOf` it: Nix downloads, caches
# and verifies per file, nothing is hashed by us, no lock file is copied into this repo. Needs
# `dynamic-derivations ca-derivations` on the daemon. Dependencies without a hash in the lock
# (git, path) are rejected by the producer.
#
# `libs` (default: the set's `sysLibs`): packages of ours a locked dependency may link instead of
# a bundled copy (openssl-sys -> openssl, mattn/go-sqlite3 -> sqlite, psych -> libyaml, table in
# builder/sys-libs.nu). Only their .drv paths reach the producer (unsafeDiscardOutputDependency,
# so nothing is built for it); those the lock asks for become inputs of the assembled derivation
# and are propagated through its exports.json, so package.nix never lists them.
{
  jig,
  nu,
  system,
  cpu,
  sysLibs ? { },
}:
let
  producers = builtins.path {
    path = ../builder;
    name = "producers";
    filter =
      p: _: builtins.match ".*/(dynamic|fetch-[a-z-]+|sys-libs|pep508|npm-registry)\\.nu" p != null;
  };

  # {name: {drv, out}} as a file in the store; the default one is built once per set
  sysLibsFile =
    libs:
    builtins.toFile "sys-libs.json" (
      builtins.toJSON (
        builtins.mapAttrs (_: p: {
          drv = builtins.unsafeDiscardOutputDependency p.drvPath;
          out = builtins.unsafeDiscardStringContext p.outPath;
        }) libs
      )
    );
  defaultSysLibs = sysLibsFile sysLibs;
  sysLibsFor = libs: if libs == null then defaultSysLibs else sysLibsFile libs;

  dynamic =
    name: script: env:
    let
      producer = derivation (
        {
          name = "${name}.drv";
          inherit system;
          seed = nu;
          inherit jig;
          builder = "${nu}/bin/nu";
          args = [ "${producers}/${script}" ];
          PATH = "${jig}/bin:${nu}/bin";
          requiredSystemFeatures = [ "builder-rpc-v0" ];
          preferLocalBuild = true;
          __contentAddressed = true;
          outputHashMode = "text";
          outputHashAlgo = "sha256";
        }
        // env
      );
    in
    builtins.outputOf producer.outPath "out";

  # for producers that end in `dynamic stage` (a second producer) instead of `dynamic submit`
  twoStage =
    name: script: env:
    builtins.outputOf (dynamic name script env) "out";

in
{
  # Cargo.lock -> a directory cargo accepts as [source.vendored-sources] (crates unpacked, with
  # .cargo-checksum.json). builder/cargo.nu points CARGO_HOME's config at it.
  cargoVendor =
    {
      source,
      libs ? null,
    }:
    dynamic "cargo-vendor" "fetch-cargo.nu" {
      inherit source;
      sysLibs = sysLibsFor libs;
    };

  # package-lock.json (v2/v3) -> { package-lock.json } with every `resolved` rewritten to
  # file:<store path>; builder/npm.nu swaps it in and `npm ci --offline` verifies integrity itself.
  # `lockFile`: for upstreams that ship none (generated by `uptrack lock`).
  npmDeps =
    {
      source,
      root ? ".",
      lockFile ? null,
    }:
    dynamic "npm-deps" "fetch-npm.nu" {
      inherit source root;
      lockFile = if lockFile == null then "" else lockFile;
    };

  # pnpm-lock.yaml (v9) -> { tarballs/, index.json }; builder/pnpm.nu seeds an offline store from it.
  pnpmDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "pnpm-deps" "fetch-pnpm.nu" { inherit source root; };

  # bun.lock -> { p/<name>@<version>/ (unpacked), index.json }; builder/bun.nu links them into
  # $BUN_INSTALL_CACHE_DIR under the names bun expects.
  bunDeps =
    {
      source,
      root ? ".",
    }:
    dynamic "bun-deps" "fetch-bun.nu" { inherit source root; };

  # deno.lock (v4+) -> a $DENO_DIR (npm/ and remote/ caches) for `deno … --cached-only`; jsr
  # hashes pin metadata that pins the files, hence two stages (builder/fetch-deno.nu, -files.nu).
  denoDeps =
    {
      source,
      root ? ".",
    }:
    twoStage "deno-deps" "fetch-deno.nu" { inherit source root; };

  # uv.lock -> { dist/, plan.json }: one artefact per package of the application's runtime closure,
  # a compatible wheel if the lock has one, else the sdist (sys-libs.nu and pyproject's
  # `tool.uv.no-binary-package` force sdists). `python`: the interpreter wheels must match.
  # Installed by builder/pyapp.nu.
  pythonDeps =
    {
      source,
      python,
      root ? ".",
      extras ? [ ],
      libs ? null,
    }:
    dynamic "python-deps" "fetch-pypi.nu" {
      inherit source root cpu;
      pythonVersion = python.version;
      extras = builtins.concatStringsSep "," extras;
      sysLibs = sysLibsFor libs;
    };

  # Gemfile.lock (with a CHECKSUMS section, Bundler >= 2.6) -> { vendor/cache/*.gem, Gemfile.lock }
  # for `bundle install --local` (builder/bundler.nu). `lockFile`: for upstreams that commit none.
  gems =
    {
      source,
      root ? ".",
      lockFile ? null,
      libs ? null,
    }:
    dynamic "gems" "fetch-gems.nu" {
      inherit source root;
      lockFile = if lockFile == null then "" else lockFile;
      gemPlatform = "${cpu}-linux";
      sysLibs = sysLibsFor libs;
    };

  # go.sum -> a GOPROXY=file:// tree (builder/go.nu builds -mod=mod against it, offline). go.sum's
  # h1: hashes are not file hashes, so .mod/.zip sha256s come from `locks` (this repo's
  # locks/go.toml, filled by `uptrack lock`); only this package's subset lands in the output, so
  # unrelated table edits rebuild nothing.
  goModules =
    {
      source,
      root ? ".",
      locks ? ../locks/go.toml,
      libs ? null,
    }:
    dynamic "go-modules" "fetch-go.nu" {
      inherit source root locks;
      sysLibs = sysLibsFor libs;
    };

  empty = builtins.path {
    path = ./empty;
    name = "empty";
  };
}
