[upstream]
purl = "pkg:github/benhoyt/inih"

[[source]]
key = "default"
url = "https://github.com/benhoyt/inih/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-jnMGOncnH+ffgtyNzA8tZPtxPCR/yq9jmPsJZE4BhXo="

[pin]
version = "62"
tag = "r62"
