[upstream]
purl = "pkg:github/libffi/libffi"

[[source]]
key = "default"
url = "https://github.com/libffi/libffi/releases/download/{tag}/libffi-{version}.tar.gz"
hash = "sha256-2LRjE2bftNUNc2wDbB+bezAzF5AkfpbMS6VOAQ/I/bE="

[pin]
version = "3.8.0"
tag = "v3.8.0"
