[upstream]
purl = "pkg:pypi/pyproject-hooks"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/p/pyproject_hooks/pyproject_hooks-{version}.tar.gz"
hash = "sha256-ezjPkORBOMvLR0OItGPF8954barqRHUVfgkguST3kKE="

[pin]
version = "1.3.3"
date = "2026-09-16"
