[upstream]
purl = "pkg:github/pkgconf/pkgconf"

[[source]]
key = "default"
url = "https://distfiles.ariadne.space/pkgconf/pkgconf-{version}.tar.xz"
hash = "sha256-zQXJWJufhuzwRMEKImmCK8nrAB7O0lgs//1liwpQwkM="

[pin]
version = "2.5.1"
