[upstream]
purl = "pkg:pypi/pathspec"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-{version}.tar.gz"
hash = "sha256-ZlV23DXXtusePlLrWS4Vu3V4TpmQ0rYk8yKY3DdkbRQ="

[pin]
version = "1.1.1"
date = "2026-04-27"
