[upstream]
purl = "pkg:github/taglib/taglib"

[[source]]
key = "default"
url = "https://github.com/taglib/taglib/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-xup/c1giZadq8jYQgsZW+NJkjw9ofpdivnBVKTVkRjU="

[pin]
version = "2.2.1"
tag = "v2.2.1"
