[upstream]
purl = "pkg:github/alsa-project/alsa-lib"

[[source]]
key = "default"
url = "https://www.alsa-project.org/files/pub/lib/alsa-lib-{version}.tar.bz2"
hash = "sha256-JozJGw0ss+QZ7towyMEKnc4W/YTFTaawLzDPD86jyRw="

[pin]
version = "1.2.16.1"
tag = "v1.2.16.1"
