[upstream]
purl = "pkg:github/mingw-w64/mingw-w64"

[[source]]
key = "default"
url = "https://github.com/mingw-w64/mingw-w64/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-ZhbY/RvTBI8ELSe0D7uzWi13sspgNZhdYg4LLK0JRng="

[pin]
version = "14.0.0"
tag = "v14.0.0"
checked = "2026-09-09"
