[upstream]
purl = "pkg:github/Kitware/CMake"

[[source]]
key = "default"
url = "https://github.com/Kitware/CMake/releases/download/{tag}/cmake-{version}.tar.gz"
hash = "sha256-ZD8EGCt7oyOrMfUm94UTT7ecujGIqFIgbvBHP+4oKhU="

[pin]
version = "4.1.2"
tag = "v4.1.2"
