[upstream]
purl = "pkg:gnu/gperf"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/gperf/gperf-{version}.tar.gz"
hash = "sha256-IWZaNoDatJCp9DTaTD4stX8xGENt5KmVtu+00T5DKJo="

[pin]
version = "3.3"
