[upstream]
purl = "pkg:github/rust-lang/rust"

[[source]]
key = "default"
url = "https://static.rust-lang.org/dist/rustc-{version}-src.tar.xz"
hash = "sha256-un3UqwdqMBUnusrsJVX8+HMiE4xYI9I9UDc2859GoEk="

[pin]
version = "1.91.0"
