[upstream]
purl = "pkg:github/rust-lang/rust"

[[source]]
key = "default"
url = "https://static.rust-lang.org/dist/rustc-{version}-src.tar.xz"
hash = "sha256-lBWYklstPu8ltF3JEPmr+FbMRoD+ax8ji9oTSlYhamM="

[pin]
version = "1.98.1"
date = "2026-09-03"
tag = "1.98.1"
