[upstream]
purl = "pkg:github/ToruNiina/toml11"

[[source]]
key = "default"
url = "https://github.com/ToruNiina/toml11/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-sgWKYxNT22nw376ttGsTdg0AMzOwp8QH3E8mx0BZJTQ="

[pin]
version = "4.4.0"
date = "2025-02-15"
tag = "v4.4.0"
