[upstream]
purl = "pkg:gnu/findutils"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/findutils/findutils-{version}.tar.xz"
hash = "sha256-VnE/TPw/fOD9I3aVmMfzZKdULcmEoljpAPjugMiq+p4="

[pin]
version = "4.10.0"
