[upstream]
purl = "pkg:gnu/sed"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/sed/sed-{version}.tar.xz"
hash = "sha256-biJrcy4c1zlGStaGK9Ghq6QteYKSLaelNRljHSSXUYE="

[pin]
version = "4.9"
