[upstream]
purl = "pkg:github/OpenPrinting/cups"
allow = "==2.4.*"

[[source]]
key = "default"
url = "https://github.com/OpenPrinting/cups/releases/download/v{version}/cups-{version}-source.tar.gz"
hash = "sha256-GSIuLeKmz3xEC3RTNaiAWQSFBF61kPxUx/Rqo1SUT+E="

[pin]
version = "2.4.19"
tag = "v2.4.19"
date = "2026-04-27"
