[upstream]
purl = "pkg:github/denoland/deployctl"

[[source]]
key = "default"
url = "https://github.com/denoland/deployctl/archive/refs/tags/{version}.tar.gz"
hash = "sha256-a/sh2m4ATBcAG5ZOjDZSpvRuC8wR3tC9sR8rssxD2cE="

[pin]
version = "1.13.1"
tag = "1.13.1"
date = "2025-01-22"
