[upstream]
purl = "pkg:github/PyO3/maturin"

[[source]]
key = "default"
url = "https://github.com/PyO3/maturin/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-YjERvdstf29LouZAOPkfi2c71vld1vy68zS3r3eJtI0="

[pin]
version = "1.15.0"
tag = "v1.15.0"
date = "2026-08-24"
checked = "2026-09-08"
