[upstream]
purl = "pkg:github/BLAKE3-team/BLAKE3"

[[source]]
key = "default"
url = "https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-IABVErXWYQFXZcwsFKfQhm3ox7UZUcW5uzVrGwsSp94="

[pin]
version = "1.8.2"
tag = "1.8.2"
