[upstream]
purl = "pkg:github/BLAKE3-team/BLAKE3"

[[source]]
key = "default"
url = "https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-a1Gu/lFZaXhdoC6Hvvr8f9x6BlzTRYzxFB8pJndJ6B8="

[pin]
version = "1.8.2"
tag = "1.8.2"
