[upstream]
purl = "pkg:npm/pnpm"
allow = "==11.*"

[[source]]
key = "default"
url = "https://registry.npmjs.org/pnpm/-/pnpm-{version}.tgz"
hash = "sha256-F6Lphh565QpyTfdgO2t7CEQc7Sdx9CJKwVd6BV+Mqlg="

[pin]
version = "11.26.0"
date = "2026-09-06"
