[upstream]
purl = "pkg:generic/pixman?url=https://cairographics.org/releases/"

[[source]]
key = "default"
url = "https://cairographics.org/releases/pixman-{version}.tar.gz"
hash = "sha256-SiXzRtCuAkbg4LBFc3USTRwj9qsAtLyfzaDMed8h7Cc="

[pin]
version = "0.46.4"
