[upstream]
purl = "pkg:github/PCRE2Project/pcre2"

[[source]]
key = "default"
url = "https://github.com/PCRE2Project/pcre2/releases/download/{tag}/pcre2-{version}.tar.bz2"
hash = "sha256-F7mA1MwwC8HtRC3wRQHSrx6PS3kMdWswdud0lf40T04="

[pin]
version = "10.48"
tag = "pcre2-10.48"
date = "2026-08-31"
