use ../core.nu *
use ../probe-cache.nu

# ./configure && make [check] && make install. Also plain-Makefile projects via steps/options.
def options []: nothing -> record { options-for autotools {flags: [], makeFlags: [], configureScript: "configure", outOfTree: true} }
# CONFIG_SHELL = bash when on PATH (configure scripts in the wild need it), else stage0's dash
# (the base userland itself). Works in the build dir, or the source when not `outOfTree`
export def --env setup []: nothing -> nothing {
  let sh = (if (which bash | is-not-empty) { tool bash } else { tool sh })
  load-env {CONFIG_SHELL: $sh, SHELL: $sh}
  let c = (ctx); cd (if (options).outOfTree { $c.build } else { $c.src })
}

# ./configure --prefix=$out (shared only), --host/--build when cross, plus `autotools.flags`.
# Autoconf scripts also get the two flags every package here wants and autoconf ignores when
# unknown: no gettext catalogues (ambient data, §3) and no .deps bookkeeping for a one-shot build
export def --env configure []: nothing -> nothing {
  let c = (ctx); let o = (options)
  let script = $"($c.src)/($o.configureScript)"
  # --host makes configure cross-aware (no running of test programs) Triple, not a nixpkgs "system"
  let host_flags = (if $c.platform.cross { [$"--host=($c.platform.triple)" "--build=x86_64-build-linux-gnu"] } else { [] })
  let cache = $"($c.build)/config.cache"
  let autoconf = (open --raw $script | str substring 0..2000 | $in =~ "Generated by GNU Autoconf")
  let key = (probe-cache key autoconf [$script])
  if $autoconf { note config.cache (if (probe-cache restore $key $cache) { "restored" } else { "cold" }) }
  x $env.CONFIG_SHELL $script $"--prefix=($c.out)" ...(if $autoconf { [$"--cache-file=($cache)" --disable-nls --disable-dependency-tracking] } else { [] }) --disable-static --enable-shared ...$host_flags ...($o.flags)
  if $autoconf { probe-cache store $key $cache }
}

# make -j (`autotools.buildTarget`, `autotools.makeFlags`)
export def build []: nothing -> nothing {
  let c = (ctx); let o = (options)
  x make $"-j($c.njobs)" ...($o.buildTarget? | default [] ) ...($o.makeFlags)
}

# make check (or `autotools.testTarget`), tests.parallel as -j
export def test []: nothing -> nothing {
  let o = (options)
  x make $"-j(test-jobs)" ...($o.testTarget? | default [check]) ...($o.makeFlags)
}

# make install (`autotools.installTarget`, `autotools.makeFlags`)
export def install []: nothing -> nothing {
  let c = (ctx); let o = (options)
  # PREFIX/prefix for configure-less Makefiles. Harmless after configure
  x make install $"PREFIX=($c.out)" $"prefix=($c.out)" ...($o.makeFlags) ...($o.installFlags? | default [])
}
