[upstream]
purl = "pkg:github/certifi/python-certifi"

[[source]]
key = "default"
url = "https://github.com/certifi/python-certifi/archive/refs/tags/{version}.tar.gz"
hash = "sha256-4qyfoy6y2s7kAkRD11GHpiho+cwupysVGVyN+oxsFu8="

[pin]
version = "2026.07.22"
