[upstream]
purl = "pkg:github/tukaani-project/xz"

[[source]]
key = "default"
url = "https://github.com/tukaani-project/xz/releases/download/{tag}/xz-{version}.tar.xz"
hash = "sha256-DhBCivleFs6+2f57v5IkqRmMPGHaG+VZOg3ZiRIxIXM="

[pin]
version = "5.8.3"
tag = "v5.8.3"
