[upstream]
purl = "pkg:github/hexpm/hex"

[[source]]
key = "default"
url = "https://github.com/hexpm/hex/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-1xiv8FWX8fk9WBoJXCUfgFN9lo7ClMVUBYb1mmr6u9U="

[pin]
version = "2.5.1"
tag = "v2.5.1"
date = "2026-07-09"
