[upstream]
purl = "pkg:pypi/installer"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/i/installer/installer-{version}.tar.gz"
hash = "sha256-C232EAS8H8NlTg6bzbd+IvCneNp+5d9XQQj6KGwdsDE="

[pin]
version = "1.0.1"
