[upstream]
purl = "pkg:github/ip7z/7zip"

[[source]]
key = "default"
url = "https://github.com/ip7z/7zip/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-MmnsCM4guQ5DuWDE5MslI8QIIbkUtZnddVPgAuCRWQU="

[pin]
version = "26.02"
tag = "26.02"
