[upstream]
purl = "pkg:gnu/gawk"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/gawk/gawk-{version}.tar.xz"
hash = "sha256-j5SjDboKkRhpSgDrnZBn4Az0LseugKFFOeUu1GlRGvc="

[pin]
version = "5.4.1"
date = "2026-07-09"
