[upstream]
purl = "pkg:github/curl/curl"

[[source]]
key = "default"
url = "https://curl.se/download/curl-{version}.tar.xz"
hash = "sha256-nrvbU5C6oeCMAecrEqYE3CNPyFVsTEqaqhhCoLe5fMo="

[pin]
version = "8.21.0"
