[upstream]
purl = "pkg:github/curl/curl"

[[source]]
key = "default"
url = "https://curl.se/download/curl-{version}.tar.xz"
hash = "sha256-qhtmpw6s6D3GJFCHRWRsCK5WHeUSq0A63/uTrIf8cuY="

[pin]
version = "8.21.0"
