[upstream]
purl = "pkg:gnu/bison"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/bison/bison-{version}.tar.xz"
hash = "sha256-m7oCFMz38QecXVkhAEUie89hlRmEDr+oDNOEnP9aW/I="

[pin]
version = "3.8.2"
