[upstream]
purl = "pkg:gnu/bash"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/bash/bash-{version}.tar.gz"
hash = "sha256-DVzYaWX4aaJs9k9Lcb57lvkKO6iz104n6OnZ1VUPMbo="

[pin]
version = "5.3"
