[upstream]
purl = "pkg:github/Mic92/repkgs"

[[source]]
key = "x86_64-linux"
url = "https://github.com/Mic92/repkgs/releases/download/seed-{version}/seed-{version}-x86_64-linux.nar.xz"
hash = "sha256-vdBeJq/0WB0QBwNe1GY00VJviN8eiay0o9v4L/Mr1C8="
unpack = true
name = "seed"

[pin]
version = "3"
