[upstream]
purl = "pkg:gnu/grep"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/grep/grep-{version}.tar.xz"
hash = "sha256-9CQnJn6JSDzD1GR+4FLyTGfmejOh+QEKNsBN1Etypqk="

[pin]
version = "3.12"
