[upstream]
purl = "pkg:github/westes/flex"

[[source]]
key = "default"
url = "https://github.com/westes/flex/releases/download/{tag}/flex-{version}.tar.gz"
hash = "sha256-HBPAUDpqF4HYocMD3YDIk6OaIUrZw8Gk3K59OmHB6xU="

[pin]
version = "2.6.4"
tag = "v2.6.4"
