[upstream]
purl = "pkg:github/anrieff/libcpuid"

[[source]]
key = "default"
url = "https://github.com/anrieff/libcpuid/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-+/TTlGk1ePPTHrSTSZmPHT2h3gKs9ouCF4ElvLWHF/g="

[pin]
version = "0.8.1"
date = "2025-08-19"
tag = "v0.8.1"
