[upstream]
purl = "pkg:github/anrieff/libcpuid"

[[source]]
key = "default"
url = "https://github.com/anrieff/libcpuid/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-RURoeuiElYT+abMsSjV8Wpn923CvSJW5/BSoUBPEHGA="

[pin]
version = "0.8.2"
date = "2026-09-13"
tag = "v0.8.2"
