[upstream]
purl = "pkg:github/elixir-lang/ex_doc"

[[source]]
key = "default"
url = "https://github.com/elixir-lang/ex_doc/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-wDdBjq62TX8m50LeszMx4f8nlUeMgElpKZ3imHNq7Hs="

[pin]
version = "0.40.4"
tag = "v0.40.4"
date = "2026-09-03"
