[upstream]
purl = "pkg:github/microsoft/mimalloc"

[[source]]
key = "default"
url = "https://github.com/microsoft/mimalloc/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-jHM19nZabrQHvyEUiCXuMmlgjKK8N4MAO4o/KYrOsXQ="

[pin]
version = "3.5.2"
date = "2026-09-12"
tag = "v3.5.2"
