[upstream]
purl = "pkg:github/microsoft/mimalloc"

[[source]]
key = "default"
url = "https://github.com/microsoft/mimalloc/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-GmLMWdUR2/VXJY7A8dZtwoV9FJIx0sxj8KWI4kG8IrU="

[pin]
version = "3.5.3"
date = "2026-09-17"
tag = "v3.5.3"
