[upstream]
purl = "pkg:github/inaka/elvis"

[[source]]
key = "default"
url = "https://github.com/inaka/elvis/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-F4c1uFlO0YWCu4zxbEHIP98WGMFHMG7PtM5b9u5ffJY="

[pin]
version = "6.0.0"
tag = "6.0.0"
date = "2026-08-21"
