[upstream]
purl = "pkg:github/besser82/libxcrypt"

[[source]]
key = "default"
url = "https://github.com/besser82/libxcrypt/releases/download/{tag}/libxcrypt-{version}.tar.xz"
hash = "sha256-EPgsI4eMBRAOxApyhgD3GTGGxH5+e/A5nca/ywPFJSw="

[pin]
version = "4.5.2"
date = "2025-11-10"
tag = "v4.5.2"
