[upstream]
purl = "pkg:github/fribidi/fribidi"

[[source]]
key = "default"
url = "https://github.com/fribidi/fribidi/releases/download/{tag}/fribidi-{version}.tar.xz"
hash = "sha256-GxzeWyNdQEeekb4vDoijCeMhTIq0cOyKJ0TYKlqeoFw="

[pin]
version = "1.0.16"
tag = "v1.0.16"
