[upstream]
purl = "pkg:github/Perl/perl5"
allow = "==5.40.*"

[[source]]
key = "default"
url = "https://www.cpan.org/src/5.0/perl-{version}.tar.xz"
hash = "sha256-z0Us/0FtHRdZhbtYmHNJI24+bldmeFaYh3I5DMUYf04="

[pin]
version = "5.40.2"
