[upstream]
purl = "pkg:gnu/coreutils"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-{version}.tar.xz"
hash = "sha256-Me7KhfG1FwcGTEXzLj/STDtkOyCIxdRFoD8WEZt8Oh4="

[pin]
version = "9.12"
date = "2026-09-14"
