[upstream]
purl = "pkg:gnu/coreutils"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-{version}.tar.xz"
hash = "sha256-TFDtvw5E4y9UPfMyOV+KiMnIeSum54fXSOIbT7qRsXA="

[pin]
version = "9.7"
