[upstream]
purl = "pkg:pypi/rpds-py"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-{version}.tar.gz"
hash = "sha256-gTUbK9VVGF6irxjzF0gJMjonYRG2K1ifWZXmvReZUtM="

[pin]
version = "2026.6.3"
