[upstream]
purl = "pkg:github/nemtrif/utfcpp"

[[source]]
key = "default"
url = "https://github.com/nemtrif/utfcpp/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-0NbbQMsucrbOGEWAVZGSFp7f4dp31XrurPVVjcYsH+I="

[pin]
version = "4.1.1"
tag = "v4.1.1"
