[upstream]
purl = "pkg:github/libarchive/libarchive"

[[source]]
key = "default"
url = "https://github.com/libarchive/libarchive/releases/download/v{version}/libarchive-{version}.tar.xz"
hash = "sha256-LJU8SE3vfvc0aaYy1rSl8w8MU6v4ckWPMlxl/NJHoiI="

[pin]
version = "3.8.9"
tag = "v3.8.9"
date = "2026-07-28"
