[upstream]
purl = "pkg:github/nodejs/node"
allow = ">=24,<25"

[[source]]
key = "default"
url = "https://nodejs.org/dist/v{version}/node-v{version}.tar.xz"
hash = "sha256-INHHknz9Envnx8FfQZBP2qd3MShed+vBPkubR+gROcM="

[pin]
version = "24.20.0"
