[upstream]
purl = "pkg:gnu/make"

[[source]]
key = "default"
url = "https://ftp.gnu.org/gnu/make/make-{version}.tar.gz"
hash = "sha256-+Cg7R8wougcWcFf6u5B3lVX6RRgMRYZ1CD+e21URP5A="

[pin]
version = "4.4.1"
