[upstream]
purl = "pkg:gnu/libiconv"

[[source]]
key = "default"
url = "https://ftpmirror.gnu.org/libiconv/libiconv-{version}.tar.gz"
hash = "sha256-8LQi9LEIysWa4iIj7LXdWJtmR6UtTt7vvkhXaaa1cRg="

[pin]
version = "1.19"
date = "2026-03-07"
