[upstream]
purl = "pkg:github/junegunn/fzf"

[[source]]
key = "default"
url = "https://github.com/junegunn/fzf/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-WxQiF8MGhken2PqpxnjP+toQC18RpIYJqnnJTOBLKO8="

[pin]
version = "0.74.3"
tag = "v0.74.3"
