[upstream]
purl = "pkg:pypi/flit-core"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/f/flit_core/flit_core-{version}.tar.gz"
hash = "sha256-xzSUGH/gdzHptvyNW1h1d0JXIaNxT4DY9Jic0MLzGjQ="

[pin]
version = "4.0.2"
