[upstream]
purl = "pkg:github/Mic92/formatelf"

[[source]]
key = "default"
url = "https://github.com/Mic92/formatelf/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-wWCpCxVogWKo/ivGfmAmD8YE8H4CQfs52lMdKsELK/w="

[pin]
version = "0.1.0"
tag = "v0.1.0"
checked = "2026-09-09"
