[upstream]
purl = "pkg:github/google/re2"

[[source]]
key = "default"
url = "https://github.com/google/re2/releases/download/{tag}/re2-{tag}.tar.gz"
hash = "sha256-0J1HVk+eR7VN0ymucW9dNlT36j16XIfCzcs1EVyEIEU="

[pin]
version = "2025.11.05"
date = "2025-11-05"
tag = "2025-11-05"
