[upstream]
purl = "pkg:github/denoland/deno"

[[source]]
key = "x86_64-linux"
url = "https://github.com/denoland/deno/releases/download/v{version}/deno-x86_64-unknown-linux-gnu.zip"
hash = "sha256-Cl52c5kKd5X+IjmNtTGTV7BewJwWsMuHatZeXgKW0DM="

[[source]]
key = "aarch64-linux"
url = "https://github.com/denoland/deno/releases/download/v{version}/deno-aarch64-unknown-linux-gnu.zip"
hash = "sha256-LV0KSWb5et2PoTzKSszWyv5k74d4l0pJwyMFgEoBq2o="

[pin]
version = "2.9.7"
date = "2026-09-17"
tag = "v2.9.7"
