[upstream]
purl = "pkg:github/BurntSushi/ripgrep"

[[source]]
key = "default"
url = "https://github.com/BurntSushi/ripgrep/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-BsSIbZwB6s8i3dDTRYJ1EdVbJmiO0oxcLu6qiYlPkOI="

[pin]
version = "15.2.0"
tag = "15.2.0"
