[upstream]
purl = "pkg:github/libgit2/libgit2"

[[source]]
key = "default"
url = "https://github.com/libgit2/libgit2/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-kBQqTxMIWMCZJA1SuxVb29Y7k+V1Y2qVR2EntoY4FUo="

[pin]
version = "1.9.7"
date = "2026-08-13"
tag = "v1.9.7"
