[upstream]
purl = "pkg:github/python/cpython"
allow = "==3.14.*"

[[source]]
key = "default"
url = "https://www.python.org/ftp/python/{version}/Python-{version}.tar.xz"
hash = "sha256-lJP052bZrUsDASpKauL7Xa6pI3QMQW1Ho3o7Dsr062Y="

[pin]
version = "3.14.7"
