[upstream]
purl = 'pkg:generic/util-linux?url=https://github.com/util-linux/util-linux/tags&regex=v([0-9.]+)\.tar\.gz'

[[source]]
key = "default"
url = "https://www.kernel.org/pub/linux/utils/util-linux/v{major}.{minor}/util-linux-{version}.tar.xz"
hash = "sha256-CG6jB8tsF58N+bhVMzN/ccKqjbLc9NlhhW2EF/uEv9c="

[pin]
version = "2.42.3"
