[upstream]
purl = "pkg:pypi/packaging"

[[source]]
key = "default"
url = "https://files.pythonhosted.org/packages/source/p/packaging/packaging-{version}.tar.gz"
hash = "sha256-lO3CVkJK84di6zEwbu0ovrnw78UKiDdJLJ1v1gBK7Xk="

[pin]
version = "26.3"
