[upstream]
purl = "pkg:github/ninja-build/ninja"

[[source]]
key = "default"
url = "https://github.com/ninja-build/ninja/archive/refs/tags/{tag}.tar.gz"
hash = "sha256-GhAF5wUT19E02ZekW+ywsCMVGYrt56hES+MHCH4lNG4="

[pin]
version = "1.13.1"
tag = "v1.13.1"
