[upstream]
purl = "pkg:github/sqlite/sqlite"

[[source]]
key = "default"
url = "https://github.com/sqlite/sqlite/archive/refs/tags/version-{version}.tar.gz"
hash = "sha256-WECpqZ4jIa29oQAPkT4RRVBVvGrtf3fENtldqiDPUwE="

[pin]
version = "3.53.3"
tag = "version-3.53.3"
